# Generated by Django 3.1.7 on 2021-04-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='owner',
        ),
    ]
