# Generated by Django 3.1.7 on 2021-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_auto_20210411_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_account',
            field=models.CharField(default='SOME STRING', max_length=266),
        ),
        migrations.AddField(
            model_name='expense',
            name='bank_account',
            field=models.CharField(default='SOME STRING', max_length=266),
        ),
        migrations.AddField(
            model_name='userincome',
            name='bank_account',
            field=models.CharField(default='SOME STRING', max_length=266),
        ),
    ]
