# Generated by Django 3.1.7 on 2021-04-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0006_expense_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='userincome',
            name='recurring',
            field=models.CharField(default='SOME STRING', max_length=266),
        ),
    ]
