# Generated by Django 3.1.7 on 2021-04-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0008_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='amount',
            field=models.CharField(default='SOME Amount', max_length=266),
        ),
    ]
