# Generated by Django 3.1.7 on 2021-04-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0010_event_eventmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.expense'),
        ),
    ]
